name: Publish Docker image
on:
  push:
    branches:
      - "*"

jobs:
  push_to_registry:
    name: Publish image to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t ghcr.io/duccltd/fdb-ch-proto-export:latest .

      - name: Docker login
        run: echo ${{ secrets.ACTOR_TOKEN }} | docker login ghcr.io -u ${{ secrets.ACTOR_NAME }} --password-stdin

      - name: Docker push
        run: docker push ghcr.io/duccltd/fdb-ch-proto-export:latest
